package com.auroali.sanguinisluxuria;

import net.minecraft.entity.damage.DamageType;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;

public class BLResources {
    public static final Identifier HAS_BLOOD_ID = id("has_blood");
    public static final Identifier GOOD_BLOOD_ID = id("good_blood");
    public static final Identifier TOXIC_BLOOD_ID = id("toxic_blood");
    public static final Identifier BLOOD_COMPONENT_ID = id("blood");
    public static final Identifier VAMPIRE_COMPONENT_ID = id("vampire");
    public static final Identifier ICONS = id("textures/gui/icons.png");
    public static final Identifier MASK_ONE_ID = id("mask_1");
    public static final Identifier MASK_TWO_ID = id("mask_2");
    public static final Identifier MASK_THREE_ID = id("mask_3");
    public static final Identifier BLOOD_BAG_ID = id("blood_bag");
    public static final Identifier BLOOD_DRAIN_SOUND = id("drain_blood");
    public static final Identifier BLOOD_STORAGE_ITEM_MODEL_PREDICATE = id("blood_storage_item_fill");
    public static final Identifier VAMPIRES_GET_HUNGER_FROM_ID = id("vampires_get_hunger_from");
    public static final Identifier SUN_BLOCKING_HELMETS = id("sun_blocking_helmets");
    public static final Identifier BLOOD_BOTTLE_ID = id("blood_bottle");
    public static final Identifier ITEM_GROUP_ID = id(Bloodlust.MODID);
    public static final Identifier BLOOD_SICKNESS_ID = id("blood_sickness");
    public static final Identifier BLOOD_SPLATTER_ID = id("blood_splatter");
    public static final Identifier CAN_DROP_BLOOD = id("can_drop_blood");
    public static final Identifier BLESSED_WATER_ID = id("blessed_water");
    public static final Identifier BLOOD_PROTECTION_ID = id("blessed_blood");
    public static final Identifier VAMPIRE_MASKS_ID = id("vampire_masks");
    public static final Identifier VAMPIRE_ABILITY_REGISTRY_ID = id("vampire_ability");
    public static final Identifier VAMPIRE_HEALTH_1_ID = id("health_1");
    public static final Identifier VAMPIRE_ABILITY_ARGUMENT_ID = id("ability_argument");
    public static final Identifier VAMPIRE_HEALTH_2_ID = id("health_2");
    public static final Identifier VAMPIRE_STRENGTH_1_ID = id("strength_1");
    public static final Identifier ABILITIES_SCREEN = id("textures/gui/abilities.png");
    public static final Identifier ABILITIES_BG = id("textures/gui/abilities_bg.png");
    public static final Identifier TELEPORT_ID = id("teleport");
    public static final Identifier TELEPORT_COOLDOWN_1_ID = id("teleport_cooldown_1");
    public static final Identifier TELEPORT_COOLDOWN_2_ID = id("teleport_cooldown_2");
    public static final Identifier TELEPORT_RANGE_1_ID = id("teleport_range_1");
    public static final Identifier TELEPORT_RANGE_2_ID = id("teleport_range_2");
    public static final Identifier TELEPORT_RANGE_TAG_ID = id("teleport_range_increase");
    public static final Identifier VAMPIRE_STRENGTH_2_ID = id("vampire_strength_2");
    public static final Identifier BECOME_VAMPIRE_CRITERION_ID = id("become_vampire");
    public static final Identifier ALTAR_ID = id("altar");
    public static final Identifier MORE_BLOOD_ID = id("more_blood");
    public static final Identifier ALTAR_RECIPE_ID = id("altar_recipe");
    public static final Identifier TWISTED_BLOOD_ID = id("twisted_blood_bottle");
    public static final Identifier PEDESTAL_ID = id("pedestal");
    public static final Identifier TRANSFER_EFFECTS_ID = id("transfer_effects");
    public static final Identifier BITE_ID = id("bite");
    public static final Identifier SUN_PROTECTION_ID = id("sun_protection");
    public static final Identifier BLOOD_DRAIN_ID = id("blood_drain");
    public static final Identifier BLESSED_BLOOD_ID = id("blessed_blood_bottle");
    public static final Identifier DAMAGE_REDUCTION_ID = id("damage_reduction");
    public static final Identifier ALTAR_BEATS_SOUND = id("altar_beats");
    public static final Identifier BLOOD_STILL = id("blood");
    public static final Identifier BLOOD_FLOWING = id("blood_flowing");
    public static final Identifier BLOOD_STILL_TEXTURE = id("block/blood_still");
    public static final Identifier BLOOD_FLOWING_TEXTURE = id("block/blood_flowing");
    public static final Identifier BLOOD_CAULDRON_ID = id("blood_cauldron");
    public static final Identifier UNLOCK_VAMPIRE_ABILITY_ID = id("unlock_ability");
    public static final Identifier RESET_ABILITIES_ID = id("reset_abilities");
    public static final Identifier ABILITY_SYNC_CHANNEL = id("ability_sync_id");
    public static final Identifier TELEPORTS_ON_DRAIN_ID = id("teleporting_blood");
    public static final Identifier BLEEDING_ID = id("bleeding");
    public static final Identifier BLEEDING_SOUND = id("bleeding");
    public static final Identifier INFECT_ENTITY_ID = id("infect_entity");
    public static final Identifier VAMPIRE_VILLAGER = id("vampire_villager");
    public static final Identifier VAMPIRE_VILLAGER_TEXTURE = id("textures/entity/vampire_villager.png");
    public static final Identifier VAMPIRE_MERCHANT_TEXTURE = id("textures/entity/vampire_merchant.png");
    public static final Identifier VAMPIRE_VILLAGER_SPAWN_EGG = id("vampire_villager_spawn_egg");
    public static final Identifier VAMPIRE_VILLAGER_SPAWN = id("vampire_villager_spawn");
    public static final Identifier VAMPIRE_CONVERT_SOUND = id("entity_converted_to_vampire");
    public static final Identifier PENDANT_OF_PIERCING = id("pendant_of_piercing");
    public static final Identifier UNBECOME_VAMPIRE_CRITERION_ID = id("unbecome_vampire");
    public static final Identifier BLESSED_WATER_TWO_ID = id("strong_blessed_water");
    public static final Identifier PENDANT_OF_TRANSFUSION = id("pendant_of_transfusion");
    public static final Identifier DOWNED_RESISTANCE_ID = id("downed_resistance");
    public static final Identifier SERRATED_ID = id("serrated");
    public static final Identifier VAMPIRE_MERCHANT = id("vampire_merchant");
    public static final Identifier BLOOD_PETAL_ID = id("blood_petal");
    public static final Identifier SILVER_INGOT_ID = id("silver_ingot");
    public static final Identifier SILVER_BLOCK_ID = id("silver_block");
    public static final Identifier RAW_SILVER_ID = id("raw_silver");
    public static final Identifier SILVER_ORE_ID = id("silver_ore");
    public static final Identifier DEEPSLATE_SILVER_ORE_ID = id("deepslate_silver_ore");
    public static final Identifier SILVER_SHOVEL_ID = id("silver_shovel");
    public static final Identifier SILVER_PICKAXE_ID = id("silver_pickaxe");
    public static final Identifier SILVER_SWORD_ID = id("silver_sword");
    public static final Identifier SILVER_AXE_ID = id("silver_axe");
    public static final Identifier SILVER_HOE_ID = id("silver_hoe");
    public static final Identifier BLESSED_DAMAGE_ID = id("blessed_damage");
    public static final Identifier RAW_SILVER_BLOCK_ID = id("raw_silver_block");
    public static final RegistryKey<DamageType> BLOOD_DRAIN_DAMAGE_KEY = RegistryKey.of(RegistryKeys.DAMAGE_TYPE, id("blood_drain"));
    public static final RegistryKey<DamageType> BLESSED_WATER_DAMAGE_KEY = RegistryKey.of(RegistryKeys.DAMAGE_TYPE, id("blessed_water"));
    public static final RegistryKey<DamageType> BITE_DAMAGE_KEY = RegistryKey.of(RegistryKeys.DAMAGE_TYPE, id("bite"));
    public static final RegistryKey<DamageType> TELEPORT_DAMAGE_KEY = RegistryKey.of(RegistryKeys.DAMAGE_TYPE, id("blink_piercing"));
    public static final Identifier VAMPIRES_WEAK_TO_ID = id("vampires_weak_to");
    public static final Identifier ACTIVATE_ABILITY_C2S = id("activate_ability");
    public static final Identifier DRAIN_BLOOD_C2S = id("drain_blood");
    public static final Identifier UNLOCK_ABILITY_C2S = id("unlock_ability");
    public static final Identifier BIND_ABILITY_C2S = id("bind_ability");

    public static Identifier id(String path) {
        return new Identifier(Bloodlust.MODID, path);
    }
}
